---
title: "Brief Bio"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Research
Kendra Wu is a theoretical epidemiologist currently working as [Postdoctoral Researcher in Statistical/ Mathematical Modelling of Infectious Diseases](https://ergo.tghn.org/contact/kendra-wu) at the [Centre for Tropical Medicine and Global Health](https://www.tropicalmedicine.ox.ac.uk) of [Nuffield Department of Clinical Medicine](https://www.ndm.ox.ac.uk) at [University of Oxford](http://www.ox.ac.uk). Her research uses mathematics and statistics to study the who, when, where, and why of various infectious diseases. In greater details, she combines empirical data with computational tools, such as mathematical and statistical models, to study the transmission mechanisms of infectious diseases in order to quantify the risk, severity, and patterns of the spread of diseases under different scenarios. These investigations aim to gain insights into the science of infectious disease transmission, inform the design of more effective treatment options, prevention strategies, and control interventions, as well as to prepare the community and the healthcare sector for the amount and nature of the casualties they will get in case of an outbreak. 

Kendra's focus has been on emerging and re-emerging pathogens, including respiratory pathogens, and more recently filoviruses and other priority pathogens focus by the World Health Organization and UK Vaccine Network. Currently at Oxford, she is a key member of a multi-institution NIHR project Adaptive Design And Genomics in Outbreaks (**ADAGIO**), in which she is designing, implementing, and evaluating a novel vaccination trial that combines approaches from clinical trial methodology, infectious disease epidemiology, and applied public health, so that it can be implemented in resource-poor countries effectively during an emerging or on-going epidemic. 

Aside from infectious diseases, Kendra is also involved in research in geriatric medicine, human rights, ethics, and healthcare in conflicts/ disasters.

# Education \& Training
Kendra received her degree in clinical geriatric medicine and PhD in community medicine with a focus of infectious disease epidemiology from [The University of Hong Kong](http://www.hku.hk), where she was a Swire Schoar and a Postgraduate Scholarship recipient. She also holds a Postgraduate Diploma (PGDip) in Epidemology from [London School of Hygiene \& Tropical Medicine](https://www.lshtm.ac.uk), and an undergraduate and a Master's degree in engineering from [The University of Michigan, Ann Arbor](http://umich.edu), USA. She was a visiting researcher at MRC Centre for Outbreak Analysis and Modelling (now [MRC Centre for Global Infectious Disease Analysis](https://www.imperial.ac.uk/mrc-outbreaks)) of [Imperial College London](http://www.imperial.ac.uk) in 2010-2011. 